{
 "title": "Rastlinjak",
 "description": "Monitoring rastlinjaka v vrtu",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperatura - zrak",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"node_data\")\r\n  |> range(start: -48h)  // Adjust this to your desired time range (e.g., -24h, -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"air_temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1\")\r\n  |> aggregateWindow(every: 1m, fn: mean)  // Adjust 'every' and 'fn' as needed\r\n  |> yield(name: \"temp\")\r\n"
    }
   ]
  },
  {
   "title": "Vlaga - zrak",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"node_data\")\r\n  |> range(start: -48h)  // Adjust this to your desired time range (e.g., -24h, -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"air_humidity\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1\")\r\n  |> aggregateWindow(every: 1m, fn: mean)  // Adjust 'every' and 'fn' as needed\r\n  |> yield(name: \"hum\")\r\n"
    }
   ]
  },
  {
   "title": "Zračni tlak",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"node_data\")\r\n  |> range(start: -48h)  // Adjust this to your desired time range (e.g., -24h, -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"air_pressure\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1\")\r\n  |> aggregateWindow(every: 1m, fn: mean)  // Adjust 'every' and 'fn' as needed\r\n  |> yield(name: \"press\")\r\n"
    }
   ]
  },
  {
   "title": "Vlaga - zemlja",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"node_data\")\r\n  |> range(start: -48h)  // Adjust this to your desired time range (e.g., -24h, -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"earth_humidity\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1\")\r\n  |> aggregateWindow(every: 1m, fn: mean)  // Adjust 'every' and 'fn' as needed\r\n  |> yield(name: \"Ehum\")\r\n"
    }
   ]
  },
  {
   "title": "Betrija",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"node_data\")\r\n  |> range(start: -48h)  // Adjust this to your desired time range (e.g., -24h, -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_voltage\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"1\")\r\n  |> aggregateWindow(every: 1m, fn: mean)  // Adjust 'every' and 'fn' as needed\r\n  |> yield(name: \"volt\")\r\n"
    }
   ]
  }
 ]
}